  name: Deploy automático

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Deploy via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              # --- DEPLOY BACKEND ---
              cd www/drive-wise/back
              
              echo "📥 [BACK] Atualizando código..."
              git pull origin main

              echo "📦 [BACK] Instalando dependências..."
              npm install

              echo "⚙️ [BACK] Gerando Prisma..."
              npx prisma generate

              echo "🔨 [BACK] Gerando o Build..."
              npm run build

              echo "🔄 [BACK] Reiniciando api..."
              pm2 reload api-drivewise

              # Use caminhos COMPLETOS (ex: /root/www/...)
              REPO_PATH="/root/www/drive-wise/front"
              TARGET_PATH="/var/www/drivewise.jadson.cloud"
             
              echo "📂 Entrando no repositório..."
              cd $REPO_PATH || { echo "Erro: Pasta do repositório não encontrada"; exit 1; }
            
              git pull origin main
              npm install
              npm run build
            
              echo "🚚 Organizando pasta de produção..."
              # Garante que a pasta pai (/var/www) existe
              sudo mkdir -p /var/www
            
              # Em vez de apagar a pasta toda, vamos limpar o CONTEÚDO dela
              # Isso evita erros de permissão no diretório pai
              sudo mkdir -p $TARGET_PATH
              sudo rm -rf $TARGET_PATH/*
              
              # Copia o CONTEÚDO da dist para dentro do target
              sudo cp -r dist/* $TARGET_PATH/
            
              echo "🔐 Permissões e Nginx..."
              sudo chown -R www-data:www-data $TARGET_PATH
              sudo nginx -t && sudo systemctl restart nginx
